/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavbarRouteRouteImport } from './routes/_navbar/route'
import { Route as NavbarIndexRouteImport } from './routes/_navbar/index'
import { Route as NavbarDatabaseIndexRouteImport } from './routes/_navbar/database/index'
import { Route as NavbarDatabaseIdIndexRouteImport } from './routes/_navbar/database/$id/index'
import { Route as NavbarDatabaseIdTestsTestIdIndexRouteImport } from './routes/_navbar/database/$id/tests/$testId/index'
import { Route as RawDatabaseIdTestsTestIdGroupsRouteRouteImport } from './routes/_raw/database/$id/tests/$testId/groups/route'
import { Route as RawDatabaseIdTestsTestIdGroupsGroupIdKeyRouteImport } from './routes/_raw/database/$id/tests/$testId/groups/$groupId/key'
import { Route as RawDatabaseIdTestsTestIdGroupsGroupIdTestRouteImport } from './routes/_raw/database/$id/tests/$testId/groups/$groupId/test'

const NavbarRouteRoute = NavbarRouteRouteImport.update({
  id: '/_navbar',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarIndexRoute = NavbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarRouteRoute,
} as any)
const NavbarDatabaseIndexRoute = NavbarDatabaseIndexRouteImport.update({
  id: '/database/',
  path: '/database/',
  getParentRoute: () => NavbarRouteRoute,
} as any)
const NavbarDatabaseIdIndexRoute = NavbarDatabaseIdIndexRouteImport.update({
  id: '/database/$id/',
  path: '/database/$id/',
  getParentRoute: () => NavbarRouteRoute,
} as any)
const NavbarDatabaseIdTestsTestIdIndexRoute =
  NavbarDatabaseIdTestsTestIdIndexRouteImport.update({
    id: '/database/$id/tests/$testId/',
    path: '/database/$id/tests/$testId/',
    getParentRoute: () => NavbarRouteRoute,
  } as any)
const RawDatabaseIdTestsTestIdGroupsRouteRoute =
  RawDatabaseIdTestsTestIdGroupsRouteRouteImport.update({
    id: '/_raw/database/$id/tests/$testId/groups',
    path: '/database/$id/tests/$testId/groups',
    getParentRoute: () => rootRouteImport,
  } as any)
const RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute =
  RawDatabaseIdTestsTestIdGroupsGroupIdKeyRouteImport.update({
    id: '/$groupId/key',
    path: '/$groupId/key',
    getParentRoute: () => RawDatabaseIdTestsTestIdGroupsRouteRoute,
  } as any)
const RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute =
  RawDatabaseIdTestsTestIdGroupsGroupIdTestRouteImport.update({
    id: '/$groupId/test',
    path: '/$groupId/test',
    getParentRoute: () => RawDatabaseIdTestsTestIdGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NavbarIndexRoute
  '/database/': typeof NavbarDatabaseIndexRoute
  '/database/$id/': typeof NavbarDatabaseIdIndexRoute
  '/database/$id/tests/$testId/groups': typeof RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren
  '/database/$id/tests/$testId/': typeof NavbarDatabaseIdTestsTestIdIndexRoute
  '/database/$id/tests/$testId/groups/$groupId/key': typeof RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute
  '/database/$id/tests/$testId/groups/$groupId/test': typeof RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof NavbarIndexRoute
  '/database': typeof NavbarDatabaseIndexRoute
  '/database/$id': typeof NavbarDatabaseIdIndexRoute
  '/database/$id/tests/$testId/groups': typeof RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren
  '/database/$id/tests/$testId': typeof NavbarDatabaseIdTestsTestIdIndexRoute
  '/database/$id/tests/$testId/groups/$groupId/key': typeof RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute
  '/database/$id/tests/$testId/groups/$groupId/test': typeof RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_navbar': typeof NavbarRouteRouteWithChildren
  '/_navbar/': typeof NavbarIndexRoute
  '/_navbar/database/': typeof NavbarDatabaseIndexRoute
  '/_navbar/database/$id/': typeof NavbarDatabaseIdIndexRoute
  '/_raw/database/$id/tests/$testId/groups': typeof RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren
  '/_navbar/database/$id/tests/$testId/': typeof NavbarDatabaseIdTestsTestIdIndexRoute
  '/_raw/database/$id/tests/$testId/groups/$groupId/key': typeof RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute
  '/_raw/database/$id/tests/$testId/groups/$groupId/test': typeof RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database/'
    | '/database/$id/'
    | '/database/$id/tests/$testId/groups'
    | '/database/$id/tests/$testId/'
    | '/database/$id/tests/$testId/groups/$groupId/key'
    | '/database/$id/tests/$testId/groups/$groupId/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/database'
    | '/database/$id'
    | '/database/$id/tests/$testId/groups'
    | '/database/$id/tests/$testId'
    | '/database/$id/tests/$testId/groups/$groupId/key'
    | '/database/$id/tests/$testId/groups/$groupId/test'
  id:
    | '__root__'
    | '/_navbar'
    | '/_navbar/'
    | '/_navbar/database/'
    | '/_navbar/database/$id/'
    | '/_raw/database/$id/tests/$testId/groups'
    | '/_navbar/database/$id/tests/$testId/'
    | '/_raw/database/$id/tests/$testId/groups/$groupId/key'
    | '/_raw/database/$id/tests/$testId/groups/$groupId/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NavbarRouteRoute: typeof NavbarRouteRouteWithChildren
  RawDatabaseIdTestsTestIdGroupsRouteRoute: typeof RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_navbar': {
      id: '/_navbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar/': {
      id: '/_navbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarIndexRouteImport
      parentRoute: typeof NavbarRouteRoute
    }
    '/_navbar/database/': {
      id: '/_navbar/database/'
      path: '/database'
      fullPath: '/database/'
      preLoaderRoute: typeof NavbarDatabaseIndexRouteImport
      parentRoute: typeof NavbarRouteRoute
    }
    '/_navbar/database/$id/': {
      id: '/_navbar/database/$id/'
      path: '/database/$id'
      fullPath: '/database/$id/'
      preLoaderRoute: typeof NavbarDatabaseIdIndexRouteImport
      parentRoute: typeof NavbarRouteRoute
    }
    '/_navbar/database/$id/tests/$testId/': {
      id: '/_navbar/database/$id/tests/$testId/'
      path: '/database/$id/tests/$testId'
      fullPath: '/database/$id/tests/$testId/'
      preLoaderRoute: typeof NavbarDatabaseIdTestsTestIdIndexRouteImport
      parentRoute: typeof NavbarRouteRoute
    }
    '/_raw/database/$id/tests/$testId/groups': {
      id: '/_raw/database/$id/tests/$testId/groups'
      path: '/database/$id/tests/$testId/groups'
      fullPath: '/database/$id/tests/$testId/groups'
      preLoaderRoute: typeof RawDatabaseIdTestsTestIdGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_raw/database/$id/tests/$testId/groups/$groupId/key': {
      id: '/_raw/database/$id/tests/$testId/groups/$groupId/key'
      path: '/$groupId/key'
      fullPath: '/database/$id/tests/$testId/groups/$groupId/key'
      preLoaderRoute: typeof RawDatabaseIdTestsTestIdGroupsGroupIdKeyRouteImport
      parentRoute: typeof RawDatabaseIdTestsTestIdGroupsRouteRoute
    }
    '/_raw/database/$id/tests/$testId/groups/$groupId/test': {
      id: '/_raw/database/$id/tests/$testId/groups/$groupId/test'
      path: '/$groupId/test'
      fullPath: '/database/$id/tests/$testId/groups/$groupId/test'
      preLoaderRoute: typeof RawDatabaseIdTestsTestIdGroupsGroupIdTestRouteImport
      parentRoute: typeof RawDatabaseIdTestsTestIdGroupsRouteRoute
    }
  }
}

interface NavbarRouteRouteChildren {
  NavbarIndexRoute: typeof NavbarIndexRoute
  NavbarDatabaseIndexRoute: typeof NavbarDatabaseIndexRoute
  NavbarDatabaseIdIndexRoute: typeof NavbarDatabaseIdIndexRoute
  NavbarDatabaseIdTestsTestIdIndexRoute: typeof NavbarDatabaseIdTestsTestIdIndexRoute
}

const NavbarRouteRouteChildren: NavbarRouteRouteChildren = {
  NavbarIndexRoute: NavbarIndexRoute,
  NavbarDatabaseIndexRoute: NavbarDatabaseIndexRoute,
  NavbarDatabaseIdIndexRoute: NavbarDatabaseIdIndexRoute,
  NavbarDatabaseIdTestsTestIdIndexRoute: NavbarDatabaseIdTestsTestIdIndexRoute,
}

const NavbarRouteRouteWithChildren = NavbarRouteRoute._addFileChildren(
  NavbarRouteRouteChildren,
)

interface RawDatabaseIdTestsTestIdGroupsRouteRouteChildren {
  RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute: typeof RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute
  RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute: typeof RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute
}

const RawDatabaseIdTestsTestIdGroupsRouteRouteChildren: RawDatabaseIdTestsTestIdGroupsRouteRouteChildren =
  {
    RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute:
      RawDatabaseIdTestsTestIdGroupsGroupIdKeyRoute,
    RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute:
      RawDatabaseIdTestsTestIdGroupsGroupIdTestRoute,
  }

const RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren =
  RawDatabaseIdTestsTestIdGroupsRouteRoute._addFileChildren(
    RawDatabaseIdTestsTestIdGroupsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  NavbarRouteRoute: NavbarRouteRouteWithChildren,
  RawDatabaseIdTestsTestIdGroupsRouteRoute:
    RawDatabaseIdTestsTestIdGroupsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
